/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.mariopoorty.screens;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import poo.mariopoorty.minigames.LoadImage;

/**
 *
 * @author Brian Ramirez
 */
public class GuessWhoScreen extends javax.swing.JFrame {
     private static final String RESOURCEPATH = "/GuessWho/";
     private ImageIcon[][] imageSegments;
    /**
     * Creates new form GuessWhoScreen
     */
    public GuessWhoScreen() {
        initComponents();
        setTitle("GuessWho");
        setSize(1250, 650);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        
        this.imageSegments=new ImageIcon[10][10];
        initImages();
        ImageIcon image;
        int width=600;
        int height=600;
        
        image=LoadImage.loadImageAdjusted(RESOURCEPATH+"bullet.png", width, height);
        initPlayGround(image);

    }

    private void initPlayGround(ImageIcon icon) {
        jpPlayGround.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();

        int labelWidth = 50; 
        int labelHeight = 50; 

        BufferedImage bufferedImage = new BufferedImage(
            icon.getIconWidth(),
            icon.getIconHeight(),
            BufferedImage.TYPE_INT_ARGB
        );
        Graphics2D g2d = bufferedImage.createGraphics();
        g2d.drawImage(icon.getImage(), 0, 0, null);
        g2d.dispose();

        Image scaledImage = bufferedImage.getScaledInstance(labelWidth * 10, labelHeight * 10, Image.SCALE_SMOOTH);
        BufferedImage scaledBufferedImage = new BufferedImage(labelWidth * 10, labelHeight * 10, BufferedImage.TYPE_INT_ARGB);
        g2d = scaledBufferedImage.createGraphics();
        g2d.drawImage(scaledImage, 0, 0, null);
        g2d.dispose();

        ArrayList<ImageIcon> imageSegmentsList = new ArrayList<>();
        for (int row = 0; row < 10; row++) {
            for (int col = 0; col < 10; col++) {
                BufferedImage segment = scaledBufferedImage.getSubimage(col * labelWidth, row * labelHeight, labelWidth, labelHeight);
                imageSegmentsList.add(new ImageIcon(segment));
            }
        }

        Collections.shuffle(imageSegmentsList);
        
        int index = 0;
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                JLabel label = new JLabel();
                label.setPreferredSize(new Dimension(labelWidth, labelHeight));
                label.setHorizontalAlignment(SwingConstants.CENTER);
                label.setIcon(LoadImage.loadImageAdjusted(RESOURCEPATH+"misteryBox.jpg",labelWidth , labelHeight));
                imageSegments[i][j]=imageSegmentsList.get(index);
                index++;

                gbc.gridx = j;
                gbc.gridy = i;
                jpPlayGround.add(label, gbc);
            }
        }

        add(jpPlayGround);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jpImages = new javax.swing.JPanel();
        imageLabel3 = new javax.swing.JLabel();
        imageLabel5 = new javax.swing.JLabel();
        imageLabel2 = new javax.swing.JLabel();
        imageLabel1 = new javax.swing.JLabel();
        imageLabel4 = new javax.swing.JLabel();
        imageLabel6 = new javax.swing.JLabel();
        imageLabel11 = new javax.swing.JLabel();
        imageLabel10 = new javax.swing.JLabel();
        imageLabel12 = new javax.swing.JLabel();
        imageLabel9 = new javax.swing.JLabel();
        imageLabel8 = new javax.swing.JLabel();
        imageLabel7 = new javax.swing.JLabel();
        imageLabel13 = new javax.swing.JLabel();
        imageLabel14 = new javax.swing.JLabel();
        imageLabel15 = new javax.swing.JLabel();
        jpPlayGround = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMaximumSize(new java.awt.Dimension(1250, 650));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        jpImages.setBackground(new java.awt.Color(255, 153, 153));
        jpImages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 5));
        jpImages.setForeground(new java.awt.Color(204, 0, 0));

        imageLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel3MouseExited(evt);
            }
        });

        imageLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel5MouseExited(evt);
            }
        });

        imageLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel2MouseExited(evt);
            }
        });

        imageLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel1MouseExited(evt);
            }
        });

        imageLabel4.setLabelFor(this);
        imageLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel4MouseExited(evt);
            }
        });

        imageLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel6MouseExited(evt);
            }
        });

        imageLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel11MouseExited(evt);
            }
        });

        imageLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel10MouseExited(evt);
            }
        });

        imageLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel12MouseExited(evt);
            }
        });

        imageLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel9MouseExited(evt);
            }
        });

        imageLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel8MouseExited(evt);
            }
        });

        imageLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel7MouseExited(evt);
            }
        });

        imageLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel13MouseExited(evt);
            }
        });

        imageLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel14MouseExited(evt);
            }
        });

        imageLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageLabel15MouseExited(evt);
            }
        });

        jpPlayGround.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jpPlayGroundLayout = new javax.swing.GroupLayout(jpPlayGround);
        jpPlayGround.setLayout(jpPlayGroundLayout);
        jpPlayGroundLayout.setHorizontalGroup(
            jpPlayGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        jpPlayGroundLayout.setVerticalGroup(
            jpPlayGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpImagesLayout = new javax.swing.GroupLayout(jpImages);
        jpImages.setLayout(jpImagesLayout);
        jpImagesLayout.setHorizontalGroup(
            jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpImagesLayout.createSequentialGroup()
                        .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpImagesLayout.createSequentialGroup()
                                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpImagesLayout.createSequentialGroup()
                                        .addComponent(imageLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jpImagesLayout.createSequentialGroup()
                                        .addComponent(imageLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpImagesLayout.createSequentialGroup()
                                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imageLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpImagesLayout.createSequentialGroup()
                                        .addComponent(imageLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpImagesLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(imageLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpImagesLayout.createSequentialGroup()
                        .addComponent(imageLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(26, 26, 26)
                .addComponent(jpPlayGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpImagesLayout.setVerticalGroup(
            jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPlayGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpImagesLayout.createSequentialGroup()
                        .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imageLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(imageLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpImagesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imageLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imageLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imageLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpImagesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imageLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imageLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imageLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imageLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imageLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imageLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpImages, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(784, 784, 784))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jpImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 156, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.setText("Attempts :");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Select which character is the one that is hidden!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(452, 452, 452)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel15MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"waluigi.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel15MouseExited

    private void imageLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel15MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"waluigi_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel15MouseEntered

    private void imageLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel14MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"wario.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel14MouseExited

    private void imageLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel14MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"wario_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel14MouseEntered

    private void imageLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel13MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"shyguy.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel13MouseExited

    private void imageLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel13MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"shyguy_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel13MouseEntered

    private void imageLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel7MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"donkey.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel7MouseExited

    private void imageLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel7MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"donkey_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel7MouseEntered

    private void imageLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel8MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"goomba.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel8MouseExited

    private void imageLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel8MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"goomba_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel8MouseEntered

    private void imageLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel9MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"koopa.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel9MouseExited

    private void imageLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel9MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"koopa_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel9MouseEntered

    private void imageLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel12MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"chainchop.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel12MouseExited

    private void imageLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel12MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"chainchop_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel12MouseEntered

    private void imageLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel10MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"bobonmb.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel10MouseExited

    private void imageLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel10MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"bobonmb_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel10MouseEntered

    private void imageLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel11MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"bullet.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel11MouseExited

    private void imageLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel11MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"bullet_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel11MouseEntered

    private void imageLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel6MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"daisy.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel6MouseExited

    private void imageLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel6MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"daisy_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel6MouseEntered

    private void imageLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel4MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"bowser.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel4MouseExited

    private void imageLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel4MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"bowser_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel4MouseEntered

    private void imageLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel1MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"mario.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel1MouseExited

    private void imageLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel1MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"mario_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel1MouseEntered

    private void imageLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel2MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"luigi.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel2MouseExited

    private void imageLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel2MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"luigi_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel2MouseEntered

    private void imageLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel5MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"toad.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel5MouseExited

    private void imageLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel5MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"toad_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel5MouseEntered

    private void imageLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel3MouseExited
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"peach.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel3MouseExited

    private void imageLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabel3MouseEntered
        // TODO add your handling code here:
        int width=100;
        int height=100;
        ImageIcon image = LoadImage.loadImageAdjusted(RESOURCEPATH+"peach_dimmed.png", width, height);
        ((JLabel)evt.getSource()).setIcon(image);
    }//GEN-LAST:event_imageLabel3MouseEntered

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessWhoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessWhoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessWhoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessWhoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessWhoScreen().setVisible(true);
            }
        });
    }
    void initImages(){
            ImageIcon image;
        int width=100;
        int height=100;
        
        image=LoadImage.loadImageAdjusted(RESOURCEPATH+"mario.png", width, height);
        imageLabel1.setIcon(image);
        
        image=LoadImage.loadImageAdjusted(RESOURCEPATH+"luigi.png", width, height);
        imageLabel2.setIcon(image);
        
        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "peach.png", width, height);
        imageLabel3.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "bowser.png", width, height);
        imageLabel4.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "toad.png", width, height);
        imageLabel5.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "daisy.png", width, height);
        imageLabel6.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "donkey.png", width, height);
        imageLabel7.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "goomba.png", width, height);
        imageLabel8.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "koopa.png", width, height);
        imageLabel9.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "bobonmb.png", width, height);
        imageLabel10.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "bullet.png", width, height);
        imageLabel11.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "chainchop.png", width, height);
        imageLabel12.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "shyguy.png", width, height);
        imageLabel13.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "wario.png", width, height);
        imageLabel14.setIcon(image);

        image = LoadImage.loadImageAdjusted(RESOURCEPATH + "waluigi.png", width, height);
        imageLabel15.setIcon(image);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel1;
    private javax.swing.JLabel imageLabel10;
    private javax.swing.JLabel imageLabel11;
    private javax.swing.JLabel imageLabel12;
    private javax.swing.JLabel imageLabel13;
    private javax.swing.JLabel imageLabel14;
    private javax.swing.JLabel imageLabel15;
    private javax.swing.JLabel imageLabel2;
    private javax.swing.JLabel imageLabel3;
    private javax.swing.JLabel imageLabel4;
    private javax.swing.JLabel imageLabel5;
    private javax.swing.JLabel imageLabel6;
    private javax.swing.JLabel imageLabel7;
    private javax.swing.JLabel imageLabel8;
    private javax.swing.JLabel imageLabel9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpImages;
    private javax.swing.JPanel jpPlayGround;
    // End of variables declaration//GEN-END:variables
}
