package BoardANDPawns;


import com.mycompany.proyect2.Player;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import minigames.LoadImage;

/**
 *
 * @author brian
 */
public class SelectCharacterScreen extends javax.swing.JFrame {
    private String characterSelected;
    private ArrayList<String> ListCharacters;
    private Player player;
   
    
    public SelectCharacterScreen(Player player) {
       this.ListCharacters = new ArrayList<>();
       loadCharacterNames();
       initComponents();
       this.jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(ListCharacters.toArray(new String[0])));
       this.setVisible(true);
       this.JLImages.setIcon(LoadImage.loadImageAdjusted("/firstMenuCharacters/Mario.png", 400, 400));//default
       //listener to change the image according to the combo box 
        jComboBox1.addActionListener(e -> {
            String selectedCharacter = (String) jComboBox1.getSelectedItem();
            this.JLImages.setIcon(LoadImage.loadImageAdjusted("/firstMenuCharacters/" + selectedCharacter + ".png", 400, 400));
        });

       this.setResizable(false);
       this.player=player;
       this.setTitle("Mario Poorty");
       this.tfNumber.setEditable(false);
       this.startButtom.setEnabled(false);
       this.waitLabel.setVisible(false);
       this.alreadyChosenLabel.setVisible(false);
       
    }
    private void loadCharacterNames(){//funtion to load each name
        this.ListCharacters.add("Mario");
        this.ListCharacters.add("Luigi");
        this.ListCharacters.add("Bowser");
        this.ListCharacters.add("Kamek");
        this.ListCharacters.add("Dry Bones");
        this.ListCharacters.add("Donkey Kong");
        this.ListCharacters.add("Peach");
        this.ListCharacters.add("Shy Guy");
        this.ListCharacters.add("Toad");
        this.ListCharacters.add("Yoshi");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        chooseButtom = new javax.swing.JButton();
        startButtom = new javax.swing.JButton();
        waitLabel = new javax.swing.JLabel();
        alreadyChosenLabel = new javax.swing.JLabel();
        JLImages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Jokerman", 2, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 51));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Welcome to Mario Poorty");
        jTextField1.setBorder(null);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jTextField2.setText("Select a character!");
        jTextField2.setBorder(null);

        jComboBox1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jTextField4.setText("Choose a number [1 - 100] :");

        tfNumber.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N

        chooseButtom.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        chooseButtom.setText("Choose Character");
        chooseButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtomActionPerformed(evt);
            }
        });

        startButtom.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        startButtom.setText("Start the game");
        startButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtomActionPerformed(evt);
            }
        });

        waitLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        waitLabel.setForeground(new java.awt.Color(0, 0, 0));
        waitLabel.setText("Wait for the other players!");

        alreadyChosenLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        alreadyChosenLabel.setForeground(new java.awt.Color(153, 0, 51));
        alreadyChosenLabel.setText("The character has been already chosen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(alreadyChosenLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(chooseButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waitLabel)
                            .addComponent(startButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chooseButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(alreadyChosenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(startButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(waitLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLImages, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLImages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtomActionPerformed
        try {
            player.out.writeUTF((String) jComboBox1.getSelectedItem());
            characterSelected=(String) jComboBox1.getSelectedItem();
            this.tfNumber.setEditable(true);
            this.startButtom.setEnabled(true);
            this.chooseButtom.setEnabled(false);
            player.setName((String) jComboBox1.getSelectedItem());
            this.alreadyChosenLabel.setVisible(false);
            this.jComboBox1.setEnabled(false);
        } catch (IOException ex) {
            Logger.getLogger(SelectCharacterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_chooseButtomActionPerformed

    private void startButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtomActionPerformed
        try {
            try {
                if(Integer.parseInt(tfNumber.getText())>0&&Integer.parseInt(tfNumber.getText())<=100){
                    int number = Integer.parseInt(tfNumber.getText()); 
                    player.out.writeInt(number); 
                }else{ 
                    JOptionPane.showMessageDialog(null, "The number is out of range. A random number will be sent.", "Warning", JOptionPane.WARNING_MESSAGE);
                    int randomNumber = new Random().nextInt(101); 
                    player.out.writeInt(randomNumber);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid entry. A random number will be sent.", "Warning", JOptionPane.WARNING_MESSAGE);
                int randomNumber = new Random().nextInt(101); 
                player.out.writeInt(randomNumber);
            }
        } catch (IOException ex) {
            Logger.getLogger(SelectCharacterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.startButtom.setEnabled(false);
        this.waitLabel.setVisible(true);
    }//GEN-LAST:event_startButtomActionPerformed


    public void NameCaseRejected() {
       ListCharacters.remove(characterSelected);
       SwingUtilities.invokeLater(() -> {
           this.alreadyChosenLabel.setVisible(true);
           this.jComboBox1.setEnabled(true);
           this.startButtom.setEnabled(false);
           this.chooseButtom.setEnabled(true);
           this.jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(ListCharacters.toArray(new String[0])));
       });
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLImages;
    private javax.swing.JLabel alreadyChosenLabel;
    private javax.swing.JButton chooseButtom;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton startButtom;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JLabel waitLabel;
    // End of variables declaration//GEN-END:variables
}
